#!/bin/sh

# RODAR O PHPStan
./vendor/bin/phpstan analyse --memory-limit=512M
if [ $? -ne 0 ]; then
    echo "Opá! Deu ruim aqui com PHPStan. Ajuste antes de continuar..."
    exit 1
fi

# RODAR OS TESTES
php artisan test
if [ $? -ne 0 ]; then
    echo "Opá! Deu ruim aqui com ALGUM TESTE. Ajuste antes de continuar..."
    exit 1
fi

# FORMATAR CADA ARQUIVO ALTERADO
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null 2>&1
    git add "${FILE}"
done

exit 0
